export interface FederalAnttTollOfficialOverride {
  road: string;
  uf: string;
  km: string;
  concessionaire: string;
  name: string;
  city: string;
  direction: "Crescente" | "Decrescente" | "Crescente/Decrescente";
  lat: number;
  lon: number;
}

export const FEDERAL_ANTT_OFFICIAL_EXCLUDED_IDS = new Set([
  "pr_epr_parana_l4_p05_norte",
  "pr_epr_parana_l4_p05_sul",
  "pr_epr_parana_l4_p06_leste",
  "pr_epr_parana_l4_p06_oeste",
  "pr_epr_parana_l4_p07_leste",
  "pr_epr_parana_l4_p07_oeste",
  "pr_epr_parana_l4_p08_leste",
  "pr_epr_parana_l4_p08_oeste",
]);

export const FEDERAL_ANTT_OFFICIAL_OVERRIDES: readonly FederalAnttTollOfficialOverride[] = [
  {
    road: "BR-262",
    uf: "MG",
    km: "736.9",
    concessionaire: "CONCEBRA",
    name: "P10 PERDIZES",
    city: "Perdizes",
    direction: "Crescente/Decrescente",
    lat: -19.617614,
    lon: -47.346547,
  },
  {
    road: "BR-153",
    uf: "MG",
    km: "127.9",
    concessionaire: "CONCEBRA",
    name: "P5 PRATA",
    city: "Prata",
    direction: "Crescente/Decrescente",
    lat: -19.471586,
    lon: -48.871046,
  },
  {
    road: "BR-262",
    uf: "MG",
    km: "512.85",
    concessionaire: "CONCEBRA",
    name: "P8 LUZ",
    city: "Luz",
    direction: "Crescente/Decrescente",
    lat: -19.788259,
    lon: -45.58463,
  },
  {
    road: "BR-262",
    uf: "MG",
    km: "863.5",
    concessionaire: "CONCEBRA",
    name: "P11 CAMPO FLORIDO",
    city: "Conceição das Alagoas",
    direction: "Crescente/Decrescente",
    lat: -19.776951,
    lon: -48.458219,
  },
  {
    road: "BR-262",
    uf: "MG",
    km: "389.4",
    concessionaire: "CONCEBRA",
    name: "P7 FLORESTAL",
    city: "Florestal",
    direction: "Crescente/Decrescente",
    lat: -19.909615,
    lon: -44.506725,
  },
  {
    road: "BR-153",
    uf: "MG",
    km: "227.9",
    concessionaire: "CONCEBRA",
    name: "P6 FRONTEIRA",
    city: "Fronteira",
    direction: "Crescente/Decrescente",
    lat: -20.142521,
    lon: -49.110488,
  },
  {
    road: "BR-262",
    uf: "MG",
    km: "600.8",
    concessionaire: "CONCEBRA",
    name: "P9 CAMPOS ALTOS",
    city: "Campos Altos",
    direction: "Crescente/Decrescente",
    lat: -19.647341,
    lon: -46.240088,
  },
  {
    road: "BR-60",
    uf: "GO",
    km: "43.1",
    concessionaire: "CONCEBRA",
    name: "P1 ALEXÂNIA",
    city: "Alexânia",
    direction: "Crescente/Decrescente",
    lat: -16.115707,
    lon: -48.58924,
  },
  {
    road: "BR-60",
    uf: "GO",
    km: "107.9",
    concessionaire: "CONCEBRA",
    name: "P2 GOIANÁPOLIS",
    city: "Goianápolis",
    direction: "Crescente/Decrescente",
    lat: -16.438631,
    lon: -49.019137,
  },
  {
    road: "BR-153",
    uf: "GO",
    km: "685.8",
    concessionaire: "CONCEBRA",
    name: "P4 ITUMBIARA",
    city: "Itumbiara",
    direction: "Crescente/Decrescente",
    lat: -18.268544,
    lon: -49.245811,
  },
  {
    road: "BR-153",
    uf: "GO",
    km: "553.1",
    concessionaire: "CONCEBRA",
    name: "P3 PROF JAMIL",
    city: "Piracanjuba",
    direction: "Crescente/Decrescente",
    lat: -17.16318,
    lon: -49.212582,
  },
  {
    road: "BR-364",
    uf: "MT",
    km: "316.55",
    concessionaire: "CRO",
    name: "P3",
    city: "Campo Verde",
    direction: "Crescente/Decrescente",
    lat: -15.81,
    lon: -55.31,
  },
  {
    road: "BR-50",
    uf: "GO",
    km: "226",
    concessionaire: "ECO050",
    name: "CAMPO ALEGRE",
    city: "Campo Alegre de Goiás",
    direction: "Crescente/Decrescente",
    lat: -17.77,
    lon: -47.75,
  },
  {
    road: "BR-50",
    uf: "GO",
    km: "144",
    concessionaire: "ECO050",
    name: "IPAMERI",
    city: "Ipameri",
    direction: "Crescente/Decrescente",
    lat: -17.12,
    lon: -47.72,
  },
  {
    road: "BR-101",
    uf: "ES",
    km: "171.7",
    concessionaire: "ECOVIAS CAPIXABA",
    name: "P3 - Aracruz",
    city: "Aracruz",
    direction: "Crescente/Decrescente",
    lat: -19.563099,
    lon: -40.177621,
  },
  {
    road: "BR-101",
    uf: "ES",
    km: "320.8",
    concessionaire: "ECOVIAS CAPIXABA",
    name: "P5 - Guarapari",
    city: "Guarapari",
    direction: "Crescente/Decrescente",
    lat: -20.519316,
    lon: -40.478609,
  },
  {
    road: "BR-101",
    uf: "ES",
    km: "398.9",
    concessionaire: "ECOVIAS CAPIXABA",
    name: "P6 - Itapemirim",
    city: "Itapemirim",
    direction: "Crescente/Decrescente",
    lat: -20.878586,
    lon: -40.966118,
  },
  {
    road: "BR-101",
    uf: "ES",
    km: "452",
    concessionaire: "ECOVIAS CAPIXABA",
    name: "P7 - Mimoso do Sul",
    city: "Mimoso do Sul",
    direction: "Crescente/Decrescente",
    lat: -21.158397,
    lon: -41.280614,
  },
  {
    road: "BR-101",
    uf: "ES",
    km: "1",
    concessionaire: "ECOVIAS CAPIXABA",
    name: "P1 - Pedro Canário",
    city: "Pedro Canário",
    direction: "Crescente/Decrescente",
    lat: -18.184708,
    lon: -39.922116,
  },
  {
    road: "BR-101",
    uf: "ES",
    km: "85.8",
    concessionaire: "ECOVIAS CAPIXABA",
    name: "P2 - São Mateus",
    city: "São Mateus",
    direction: "Crescente/Decrescente",
    lat: -18.863974,
    lon: -39.938705,
  },
  {
    road: "BR-101",
    uf: "ES",
    km: "242",
    concessionaire: "ECOVIAS CAPIXABA",
    name: "P4 - Serra",
    city: "Serra",
    direction: "Crescente/Decrescente",
    lat: -20.032565,
    lon: -40.396624,
  },
  {
    road: "BR-153",
    uf: "GO",
    km: "12.5",
    concessionaire: "ECOVIAS DO ARAGUAIA",
    name: "P3 - Porangatu",
    city: "Porangatu",
    direction: "Crescente/Decrescente",
    lat: -12.943414,
    lon: -49.133122,
  },
  {
    road: "BR-80",
    uf: "GO",
    km: "155.5",
    concessionaire: "ECOVIAS DO ARAGUAIA",
    name: "P8 - Santa Rita do Novo Destino",
    city: "Santa Rita do Novo Destino",
    direction: "Crescente/Decrescente",
    lat: -14.814189,
    lon: -49.042442,
  },
  {
    road: "BR-414",
    uf: "GO",
    km: "404.08",
    concessionaire: "ECOVIAS DO ARAGUAIA",
    name: "P9 - Corumbá de Goiás",
    city: "Corumbá de Goiás",
    direction: "Crescente/Decrescente",
    lat: -16.001028,
    lon: -48.840289,
  },
  {
    road: "BR-153",
    uf: "GO",
    km: "116.12",
    concessionaire: "ECOVIAS DO ARAGUAIA",
    name: "P4 - Estrela do Norte",
    city: "Estrela do Norte",
    direction: "Crescente/Decrescente",
    lat: -13.791358,
    lon: -49.034842,
  },
  {
    road: "BR-153",
    uf: "GO",
    km: "233.4",
    concessionaire: "ECOVIAS DO ARAGUAIA",
    name: "P6 - Hidrolina",
    city: "Hidrolina",
    direction: "Crescente/Decrescente",
    lat: -14.799372,
    lon: -49.284164,
  },
  {
    road: "BR-153",
    uf: "GO",
    km: "367.5",
    concessionaire: "ECOVIAS DO ARAGUAIA",
    name: "P7 - Jaraguá",
    city: "Jaraguá",
    direction: "Crescente/Decrescente",
    lat: -15.827072,
    lon: -49.281722,
  },
  {
    road: "BR-153",
    uf: "GO",
    km: "182.04",
    concessionaire: "ECOVIAS DO ARAGUAIA",
    name: "P5 - Campinorte",
    city: "Campinorte",
    direction: "Crescente/Decrescente",
    lat: -14.372969,
    lon: -49.158264,
  },
  {
    road: "BR-364",
    uf: "GO",
    km: "92.85",
    concessionaire: "ECOVIAS DO CERRADO",
    name: "P6 - CACHOEIRA ALTA",
    city: "Cachoeira Alta",
    direction: "Crescente/Decrescente",
    lat: -18.47,
    lon: -51.08,
  },
  {
    road: "BR-364",
    uf: "GO",
    km: "156.18",
    concessionaire: "ECOVIAS DO CERRADO",
    name: "P7 - JATAÍ",
    city: "Jataí",
    direction: "Crescente/Decrescente",
    lat: -18.11,
    lon: -51.48,
  },
  {
    road: "BR-364",
    uf: "GO",
    km: "32.6",
    concessionaire: "ECOVIAS DO CERRADO",
    name: "P5 - PARANAIGUARA",
    city: "Paranaiguara",
    direction: "Crescente/Decrescente",
    lat: -18.88,
    lon: -50.76,
  },
  {
    road: "BR-364",
    uf: "RO",
    km: "452.3",
    concessionaire: "NOVA 364",
    name: "Free Flow Jarú -  P03",
    city: "Theobroma",
    direction: "Crescente/Decrescente",
    lat: -10.287172,
    lon: -62.670764,
  },
];
