sonar.projectKey=Daniellima2308_Space-Truck
sonar.projectName=Space-Truck

# Source and test paths
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx
sonar.exclusions=src/test/**,dist/**,coverage/**,node_modules/**

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Language
sonar.language=ts
sonar.typescript.tsconfigPath=tsconfig.app.json
